#!/bin/sh

# Check if a composer.json file is present
if [ -f composer.json ]; then
    # Detect composer binary
    if command -v composer >/dev/null; then
        COMPOSER_CMD='composer'
    elif command -v composer.phar >/dev/null; then
        COMPOSER_CMD='composer.phar'
    else
        echo "WARN: Composer file found but composer not installed!" 1>&2
        COMPOSER_CMD='MISSING'
        exit 0
    fi
    # Run composer if composer.json is updated
    # Install or update depending on lock file
    [ ! -f composer.lock ] && $COMPOSER_CMD install || $COMPOSER_CMD update
fi

